WIP Add test for Yamel Editor component #6091
test failing with:
Summary of all failing tests
 FAIL  packages/console-shared/src/components/editor/__tests__/YAMLEditor.spec.tsx
  ● Test suite failed to run

    Cannot find module 'monaco-editor' from 'editor.js'

      at Resolver.resolveModule
(node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous>
(node_modules/react-monaco-editor/lib/editor.js:11:21)

why the dependency can be missing??

Signed-off-by: Aurélien Pupier <apupier@redhat.com>